### PR TITLE
Code consistency

### PR DESCRIPTION
**Pull request by volbil**
This RP fixes issue discussed at #19 :)

### CODE REVIEW

**Comment by y-chan** [comment]
Sorry for late reply.
I want to apply i18n in the near future.
We need to use `"".format()` for that.
I'm sorry, please use `"".format()`

**Comment by volbil** [comment]
Hi there @y-chan, f-strings is basically new compat way of string formatting. It works in pretty much the same way as `.format()`. Here is an [example](https://github.com/y-chan/atomicswap-qt/pull/22/commits/08b36888fcf983aee8282303430382df4a1bc768#diff-1f301c97b1314c27315c77aef4a0c04cL90-R90), as you can see code essentially the same, just shorter.

**Comment by volbil** [comment]
Ohhh, I see what you mean. We will have stings with `{}` for different languages. Ok, I will update it :)

**Comment by volbil** [comment]
@y-chan done.

**Comment by y-chan** [comment]
Thank you very much!

**Pull request merged**
